[package]
name = "analizer"
version.workspace = true
authors.workspace = true
description = "Analize the key log data"
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
