[tasks.clean]
description = "clean output figures"
run = "rm -rf figs"

[tasks.lint]
description = "run linter and formatter"
run = "cargo fmt --all -- --check && cargo clippy --all-targets --all-features -- -D warnings"
