[tasks.clean]
description = "clean output figures"
run = "rm -rf figs"

[tasks.lint]
description = "run linter and formatter"
run = "cargo fmt --all -- --check && cargo clippy --all-targets --all-features -- -D warnings"

[tasks.runinfo]
description = "run analyzer with info level logging"
run = "RUST_LOG=info cargo run --release --bin analyzer -- --config config/default.toml"

[tasks.rundebug]
description = "run analyzer with debug level logging"
run = "RUST_LOG=debug cargo run --release --bin analyzer -- --config config/default.toml"
