[solver]
version = "v1"  # "v1" | "v2"
output_dir = "figs"
geometry = "row-stagger"  # "row-stagger" | "ortho" | "column-stagger"
csv_dir = "csv"

[v1]
include_fkeys = false
a_ms = 0.0
b_ms = 1.0

[v2]
# Phase 1: 指別Fitts係数
[v2.fitts_coefficients]
enable = false
# 各指の初期値（Phase 1で実装）
[v2.fitts_coefficients.values]
LThumb = [50.0, 150.0]    # [a_ms, b_ms]
LIndex = [40.0, 120.0] 
LMiddle = [45.0, 130.0]
LRing = [55.0, 145.0]
LPinky = [65.0, 160.0]
RThumb = [50.0, 150.0]
RIndex = [40.0, 120.0]
RMiddle = [45.0, 130.0]
RRing = [55.0, 145.0]
RPinky = [65.0, 160.0]

# Phase 2: 方向依存幅
[v2.directional_width]
enable = false

# Phase 3: レイヤシステム
[v2.layers]
enable = false
modifier_penalty_ms = 10.0
# モディファイア配置可能位置（Phase 3で詳細化）
modifier_rows = [3, 4]  # 親指行等

# Phase 4: 数値クラスター  
[v2.digit_cluster]
enable = false
enforce_order = true
allowed_rows = [0, 1]  # 上段、ファンクション行

# Phase 5: ビグラム近似
[v2.bigrams]
enable = false
approach = "DirectionalBucket"  # "TopMLinearization"
min_frequency = 10.0

[comparison]
enable_parallel = true
save_report = true
report_format = "html"  # "html" | "json" | "csv"