# デフォルト設定
[solver]
version = "v1"           # "v1" | "v2"
output_dir = "figs"      # 出力ディレクトリ
geometry = "row-stagger" # "row-stagger" | "ortho" | "column-stagger"
csv_dir = "csv"          # データのCSVディレクトリ

# 最適化オプション (全てデフォルト値があるのでこれらはオプション)
include_fkeys = false
include_digits = false   # 数字行も最適化に含めるか
include_alphabet = false # アルファベット(A-Z)も最適化に含めるか
max_rows = 5             # 最大行数（4-6）
align_left_edge = false  # 左端揃え (未実装)
align_right_edge = false # 右端揃え (未実装)
solution_threshold = 0.5

# 指別Fitts係数設定
[fingerwise_coeffs]
[fingerwise_coeffs.LIndex]
a_ms = 144.3
b_ms = 75.64

[fingerwise_coeffs.RIndex]
a_ms = 144.3
b_ms = 75.64

[fingerwise_coeffs.LMiddle]
a_ms = 147.0
b_ms = 79.0

[fingerwise_coeffs.RMiddle]
a_ms = 147.0
b_ms = 79.0

[fingerwise_coeffs.LRing]
a_ms = 152.0
b_ms = 90.1

[fingerwise_coeffs.RRing]
a_ms = 152.0
b_ms = 90.1

[fingerwise_coeffs.LPinky]
a_ms = 155.0
b_ms = 97.0

[fingerwise_coeffs.RPinky]
a_ms = 155.0
b_ms = 97.0

[fingerwise_coeffs.LThumb]
a_ms = 155.3
b_ms = 93.0

[fingerwise_coeffs.RThumb]
a_ms = 155.3
b_ms = 93.0
