[solver]
version = "v2"           # v2でPhase1を使用
output_dir = "figs"
geometry = "row-stagger"
csv_dir = "csv"

[v1]
include_fkeys = false
a_ms = 0.0
b_ms = 1.0

[v2]
# Phase 1: 指別Fitts係数を有効化
[v2.fitts_coefficients]
enable = true
# 各指の係数（研究ベース）
[v2.fitts_coefficients.values]
LThumb = [50.0, 140.0]  # [a_ms, b_ms]
LIndex = [40.0, 120.0]  # 人差し指：高速
LMiddle = [45.0, 130.0] # 中指
LRing = [55.0, 145.0]   # 薬指
LPinky = [65.0, 160.0]  # 小指：低速
RThumb = [50.0, 140.0]
RIndex = [40.0, 120.0]
RMiddle = [45.0, 130.0]
RRing = [55.0, 145.0]
RPinky = [65.0, 160.0]

# Phase 2以降は無効
[v2.directional_width]
enable = false

[v2.layers]
enable = false
modifier_penalty_ms = 10.0
modifier_rows = [3, 4]

[v2.digit_cluster]
enable = false
enforce_order = true
allowed_rows = [0, 1]

[v2.bigrams]
enable = false
approach = "DirectionalBucket"
min_frequency = 10.0

[comparison]
enable_parallel = true
save_report = true
report_format = "html"