# 端揃えオプションのテスト設定

[solver]
version = "v1"
timeout_seconds = 60
output_dir = "figs"
geometry = "ortho"
csv_dir = "csv"

[v1]
a_ms = 0.0
b_ms = 1.0
include_fkeys = false

# 基本機能のみ有効化
enable_fingerwise_fitts = false
enable_digit_cluster = true
enable_directional_width = false

# 基本重み設定
[v1.weights]
normal_keys = 1.0
arrow_and_digit_keys = 1.0
width_penalty = 0.0

# 数字クラスタ設定（端揃えテスト）
[v1.digit_cluster]
enable = true
enforce_sequence = true
allowed_rows = [0, 1]
enforce_horizontal = true
# 端揃えオプション（テスト用）
align_left_edge = true     # 左端揃えをテスト
align_right_edge = false   # 右端揃えは無効

# ソルバー定数設定
[v1.solver_constants]
required_arrow_blocks = 4
max_flow_per_block = 3.0
required_digit_blocks = 10
max_digit_flow_per_block = 9.0
flow_roots = 1.0
digit_flow_roots = 1.0
solution_threshold = 0.5

[v2]
# v2設定（未使用）

# 標準的な2×6 Ortholinear レイアウト（簡略版）
[geometry]
name = "ortho"

# 行0: 数字・記号行
[[geometry.rows]]
y = 0.0
cells = [
    { col = 0, finger = "LIndex" },
    { col = 1, finger = "LIndex" },
    { col = 2, finger = "LIndex" },
    { col = 3, finger = "RIndex" },
    { col = 4, finger = "RIndex" },
    { col = 5, finger = "RIndex" },
]

# 行1: アルファベット行（固定）
[[geometry.rows]]
y = 1.0
cells = [
    { col = 0, finger = "LIndex", occupied = true },  # A
    { col = 1, finger = "LIndex", occupied = true },  # S  
    { col = 2, finger = "LIndex" },
    { col = 3, finger = "RIndex" },
    { col = 4, finger = "RIndex", occupied = true },  # K
    { col = 5, finger = "RIndex", occupied = true },  # L
]

# ホームポジション（2×6、19.05mm間隔）
[geometry.homes]
LIndex = [57.15, 19.05]   # 行1 の左人差し指
RIndex = [133.35, 19.05]  # 行1 の右人差し指