[solver]
version = "v1"           # "v1" | "v2"
output_dir = "figs"      # 出力ディレクトリ
geometry = "row-stagger" # "row-stagger" | "ortho" | "column-stagger"
csv_dir = "csv"          # データのCSVディレクトリ
max_rows = 6             # 最大行数
include_digits = true    # 数字キーを最適化対象に含める
include_fkeys = false    # Fキーを最適化対象に含める

# 指別Fitts係数設定
[fingerwise_coeffs]
[fingerwise_coeffs.LIndex]
a_ms = 40.0
b_ms = 120.0

[fingerwise_coeffs.RIndex]
a_ms = 40.0
b_ms = 120.0

[fingerwise_coeffs.LMiddle]
a_ms = 45.0
b_ms = 130.0

[fingerwise_coeffs.RMiddle]
a_ms = 45.0
b_ms = 130.0

[fingerwise_coeffs.LRing]
a_ms = 55.0
b_ms = 145.0

[fingerwise_coeffs.RRing]
a_ms = 55.0
b_ms = 145.0

[fingerwise_coeffs.LPinky]
a_ms = 65.0
b_ms = 160.0

[fingerwise_coeffs.RPinky]
a_ms = 65.0
b_ms = 160.0

[fingerwise_coeffs.LThumb]
a_ms = 50.0
b_ms = 140.0

[fingerwise_coeffs.RThumb]
a_ms = 50.0
b_ms = 140.0

# v1設定
[v1]
[v1.digit_cluster]
enforce_sequence = true
enforce_horizontal = true
allowed_rows = [4]        # デフォルトでは数字行（下から4行目）
