# v1 Advanced テスト設定
# CLAUDE.md v1仕様のテスト用設定

[solver]
version = "v1_advanced"
timeout_seconds = 300
output_dir = "figs"
geometry = "row-stagger"
csv_dir = "csv"

[v1]
a_ms = 50.0
b_ms = 150.0
include_fkeys = false

[advanced]
# 指別Fitts係数の有効化
enable_fingerwise_fitts = true

# 数字クラスタの有効化
enable_digit_cluster = true

# 方向依存幅の有効化
enable_directional_width = true

# 最適化重み設定
[advanced.weights]
normal_keys = 1.0
arrow_and_digit_keys = 1.0
width_penalty = 0.01

# 指別Fitts係数設定（CLAUDE.mdデフォルト値）
[advanced.fingerwise_coeffs]
# 人差し指（最速）
[advanced.fingerwise_coeffs.LIndex]
a_ms = 40.0
b_ms = 120.0

[advanced.fingerwise_coeffs.RIndex]
a_ms = 40.0
b_ms = 120.0

# 中指
[advanced.fingerwise_coeffs.LMiddle]
a_ms = 45.0
b_ms = 130.0

[advanced.fingerwise_coeffs.RMiddle]
a_ms = 45.0
b_ms = 130.0

# 薬指
[advanced.fingerwise_coeffs.LRing]
a_ms = 55.0
b_ms = 145.0

[advanced.fingerwise_coeffs.RRing]
a_ms = 55.0
b_ms = 145.0

# 小指（最遅）
[advanced.fingerwise_coeffs.LPinky]
a_ms = 65.0
b_ms = 160.0

[advanced.fingerwise_coeffs.RPinky]
a_ms = 65.0
b_ms = 160.0

# 親指
[advanced.fingerwise_coeffs.LThumb]
a_ms = 50.0
b_ms = 140.0

[advanced.fingerwise_coeffs.RThumb]
a_ms = 50.0
b_ms = 140.0

# 数字クラスタ設定
[advanced.digit_cluster]
enable = true
enforce_sequence = true   # 1,2,3,...,9,0の順序強制
allowed_rows = [0, 1]     # 上部2行に配置
enforce_horizontal = true # 横配置強制

# 行配置の自由化設定
[advanced.row_flexibility]
enable_free_positioning = false # trueにすると行位置を最適化対象に
fixed_alphabet_rows = true      # アルファベット行を固定するか
optimizable_symbols = true      # 記号キーの行を最適化するか
min_rows_from_home = 1          # ホーム行からの最小距離
max_rows_from_home = 2          # ホーム行からの最大距離

# 最適化変数の詳細設定
[advanced.optimization_vars]
auto_tune_weights = false     # 重みの自動調整
use_frequency_scaling = true  # 頻度スケーリング
enable_bigram_penalty = false # バイグラムペナルティ
bigram_weight = 0.1           # バイグラム重み
distance_penalty_factor = 1.0 # 距離ペナルティ係数
finger_balance_weight = 0.0   # 指バランス重み

[v2]
# v2設定（使用しないが必須）

# ジオメトリ設定
[geometry]
name = "ortho"

# 4×12レイアウトでテスト
[[geometry.rows]]
y = 0.0
cells = [
    # 上段（数字・記号行）
    { col = 0, finger = "LPinky" },
    { col = 1, finger = "LRing" },
    { col = 2, finger = "LMiddle" },
    { col = 3, finger = "LIndex" },
    { col = 4, finger = "LIndex" },
    { col = 5, finger = "LIndex" },
    { col = 6, finger = "RIndex" },
    { col = 7, finger = "RIndex" },
    { col = 8, finger = "RMiddle" },
    { col = 9, finger = "RRing" },
    { col = 10, finger = "RPinky" },
    { col = 11, finger = "RPinky" },
]

[[geometry.rows]]
y = 1.0
cells = [
    # QWERTY行（固定）
    { col = 0, finger = "LPinky", occupied = true },  # Q
    { col = 1, finger = "LRing", occupied = true },   # W
    { col = 2, finger = "LMiddle", occupied = true }, # E
    { col = 3, finger = "LIndex", occupied = true },  # R
    { col = 4, finger = "LIndex", occupied = true },  # T
    { col = 5, finger = "LIndex" },
    { col = 6, finger = "RIndex" },
    { col = 7, finger = "RIndex", occupied = true },  # Y
    { col = 8, finger = "RMiddle", occupied = true }, # U
    { col = 9, finger = "RRing", occupied = true },   # I
    { col = 10, finger = "RPinky", occupied = true }, # O
    { col = 11, finger = "RPinky", occupied = true }, # P
]

[[geometry.rows]]
y = 2.0
cells = [
    # ASDF行（固定）
    { col = 0, finger = "LPinky", occupied = true },  # A
    { col = 1, finger = "LRing", occupied = true },   # S
    { col = 2, finger = "LMiddle", occupied = true }, # D
    { col = 3, finger = "LIndex", occupied = true },  # F
    { col = 4, finger = "LIndex", occupied = true },  # G
    { col = 5, finger = "LIndex" },
    { col = 6, finger = "RIndex" },
    { col = 7, finger = "RIndex", occupied = true },  # H
    { col = 8, finger = "RMiddle", occupied = true }, # J
    { col = 9, finger = "RRing", occupied = true },   # K
    { col = 10, finger = "RPinky", occupied = true }, # L
    { col = 11, finger = "RPinky" },
]

[[geometry.rows]]
y = 3.0
cells = [
    # ZXCV行（固定）
    { col = 0, finger = "LPinky", occupied = true },  # Z
    { col = 1, finger = "LRing", occupied = true },   # X
    { col = 2, finger = "LMiddle", occupied = true }, # C
    { col = 3, finger = "LIndex", occupied = true },  # V
    { col = 4, finger = "LIndex", occupied = true },  # B
    { col = 5, finger = "LIndex" },
    { col = 6, finger = "RIndex" },
    { col = 7, finger = "RIndex", occupied = true },  # N
    { col = 8, finger = "RMiddle", occupied = true }, # M
    { col = 9, finger = "RRing" },
    { col = 10, finger = "RPinky" },
    { col = 11, finger = "RPinky" },
]

# ホームポジション（Ortholinear、19.05mm間隔）
[geometry.homes]
LPinky = [0.0, 38.1]    # 行2 (ASDF行) の左小指
LRing = [19.05, 38.1]   # 行2 の左薬指
LMiddle = [38.1, 38.1]  # 行2 の左中指
LIndex = [57.15, 38.1]  # 行2 の左人差し指
LThumb = [76.2, 57.15]  # 下部中央
RThumb = [95.25, 57.15] # 下部中央
RIndex = [133.35, 38.1] # 行2 の右人差し指
RMiddle = [152.4, 38.1] # 行2 の右中指
RRing = [171.45, 38.1]  # 行2 の右薬指
RPinky = [190.5, 38.1]  # 行2 の右小指
