[solver]
version = "v2"
output_dir = "figs"

[v1]
include_fkeys = false
a_ms = 0.0
b_ms = 1.0

[v2]
# Phase 1: 指別Fitts係数を有効化
[v2.fitts_coefficients]
enable = true
[v2.fitts_coefficients.values]
LThumb = [45.0, 140.0]
LIndex = [35.0, 110.0]
LMiddle = [40.0, 120.0]
LRing = [50.0, 135.0]
LPinky = [60.0, 150.0]
RThumb = [45.0, 140.0]
RIndex = [35.0, 110.0]
RMiddle = [40.0, 120.0]
RRing = [50.0, 135.0]
RPinky = [60.0, 150.0]

# Phase 2: 方向依存幅を有効化
[v2.directional_width]
enable = true

# Phase 3: レイヤシステム（将来の例）
[v2.layers]
enable = false
modifier_penalty_ms = 8.0
modifier_rows = [4]       # 親指行のみ

[v2.digit_cluster]
enable = false

[v2.bigrams]
enable = false

[comparison]
enable_parallel = true
save_report = true
report_format = "html"
