name: Versioning

on:
  push:
    tags:
      - "*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Update version in Cargo.toml
        run: |
          sed -i '/^\[workspace\.package\]/,/^\[/ s/^version = "[^"]*"/version = "${{ steps.get_version.outputs.VERSION }}"/' Cargo.toml

      - name: Update Cargo.lock
        run: |
          cargo update -w

      - name: Commit and Push Version Updates
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add Cargo.toml Cargo.lock
          git commit -m "Update version to ${{ steps.get_version.outputs.VERSION }}" || exit 0
          git push origin HEAD:main
